import {
  Baby,
  Bath,
  BedDouble,
  Bike,
  Bird,
  Brush,
  Car,
  ChefHat,
  Coffee,
  Dumbbell,
  Droplets,
  Flower2,
  Footprints,
  Hammer,
  Laptop,
  Mail,
  Mountain,
  PawPrint,
  Phone,
  Pill,
  Recycle,
  Shirt,
  ShoppingCart,
  SprayCan,
  Star,
  Trash2,
  Utensils,
  Wheat,
  type LucideIcon,
} from 'lucide-react';
import type { ChoreIconId } from '@/lib/chores/iconIds';

export const CHORE_ICONS: Record<ChoreIconId, LucideIcon> = {
  bins: Trash2,
  vacuum: SprayCan,
  bath: Bath,
  plants: Droplets,
  laundry: Shirt,
  kitchen: Utensils,
  pets: PawPrint,
  phone: Phone,
  hike: Mountain,
  walk: Footprints,
  bike: Bike,
  car: Car,
  bed: BedDouble,
  workout: Dumbbell,
  shop: ShoppingCart,
  cook: ChefHat,
  bake: Wheat,
  coffee: Coffee,
  garden: Flower2,
  clean: Brush,
  recycle: Recycle,
  mail: Mail,
  laptop: Laptop,
  meds: Pill,
  baby: Baby,
  tools: Hammer,
  bird: Bird,
  generic: Star,
};

export const CHORE_ICON_OPTIONS: Array<{ id: ChoreIconId; label: string }> = [
  { id: 'bins', label: 'Bins' },
  { id: 'vacuum', label: 'Vacuum' },
  { id: 'bath', label: 'Bathroom' },
  { id: 'plants', label: 'Water' },
  { id: 'laundry', label: 'Laundry' },
  { id: 'kitchen', label: 'Kitchen' },
  { id: 'pets', label: 'Pets' },
  { id: 'phone', label: 'Call' },
  { id: 'hike', label: 'Hike' },
  { id: 'walk', label: 'Walk' },
  { id: 'bike', label: 'Bike' },
  { id: 'car', label: 'Car' },
  { id: 'bed', label: 'Bedding' },
  { id: 'workout', label: 'Workout' },
  { id: 'shop', label: 'Errand' },
  { id: 'cook', label: 'Cook' },
  { id: 'bake', label: 'Bake' },
  { id: 'coffee', label: 'Coffee' },
  { id: 'garden', label: 'Garden' },
  { id: 'clean', label: 'Clean' },
  { id: 'recycle', label: 'Recycle' },
  { id: 'mail', label: 'Mail' },
  { id: 'laptop', label: 'Computer' },
  { id: 'meds', label: 'Meds' },
  { id: 'baby', label: 'Kids' },
  { id: 'tools', label: 'Fix' },
  { id: 'bird', label: 'Animals' },
  { id: 'generic', label: 'Other' },
];

export const CHORE_ICON_COLORS: Record<ChoreIconId, string> = {
  bins: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/50 dark:text-emerald-300',
  vacuum: 'bg-amber-100 text-amber-700 dark:bg-amber-900/50 dark:text-amber-300',
  bath: 'bg-violet-100 text-violet-700 dark:bg-violet-900/50 dark:text-violet-300',
  plants: 'bg-sky-100 text-sky-700 dark:bg-sky-900/50 dark:text-sky-300',
  laundry: 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/50 dark:text-indigo-300',
  kitchen: 'bg-orange-100 text-orange-700 dark:bg-orange-900/50 dark:text-orange-300',
  pets: 'bg-rose-100 text-rose-700 dark:bg-rose-900/50 dark:text-rose-300',
  phone: 'bg-teal-100 text-teal-700 dark:bg-teal-900/50 dark:text-teal-300',
  hike: 'bg-lime-100 text-lime-700 dark:bg-lime-900/50 dark:text-lime-300',
  walk: 'bg-green-100 text-green-700 dark:bg-green-900/50 dark:text-green-300',
  bike: 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900/50 dark:text-cyan-300',
  car: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300',
  bed: 'bg-fuchsia-100 text-fuchsia-700 dark:bg-fuchsia-900/50 dark:text-fuchsia-300',
  workout: 'bg-red-100 text-red-700 dark:bg-red-900/50 dark:text-red-300',
  shop: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/50 dark:text-yellow-300',
  cook: 'bg-orange-100 text-orange-700 dark:bg-orange-900/50 dark:text-orange-300',
  bake: 'bg-amber-100 text-amber-800 dark:bg-amber-900/50 dark:text-amber-200',
  coffee: 'bg-stone-100 text-stone-700 dark:bg-stone-800 dark:text-stone-300',
  garden: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/50 dark:text-emerald-300',
  clean: 'bg-sky-100 text-sky-700 dark:bg-sky-900/50 dark:text-sky-300',
  recycle: 'bg-green-100 text-green-700 dark:bg-green-900/50 dark:text-green-300',
  mail: 'bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300',
  laptop: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300',
  meds: 'bg-rose-100 text-rose-700 dark:bg-rose-900/50 dark:text-rose-300',
  baby: 'bg-pink-100 text-pink-700 dark:bg-pink-900/50 dark:text-pink-300',
  tools: 'bg-neutral-100 text-neutral-700 dark:bg-neutral-800 dark:text-neutral-300',
  bird: 'bg-amber-100 text-amber-700 dark:bg-amber-900/50 dark:text-amber-300',
  generic: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300',
};

export const WEEKDAY_LABELS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
